# https://docs.gitlab.com/ci/yaml

stages: # List of stages for jobs, and their order of execution
  - default

# Run health checks on that revision which is pinned in submodules
check-health:
  image: docker:cli
  stage: default
  services:
    - docker:dind
  before_script:
    - test ! -z $cicdtoken
    - git config --global url."https://gitlab-ci-token:${cicdtoken}@${CI_SERVER_HOST}/".insteadOf "https://${CI_SERVER_HOST}/"
    - git submodule update --init --recursive app model
  script:
    # Try to build the images
    - docker compose build --pull
    # Wait for health checks to pass
    - docker compose up --wait
    # Ok
    - docker compose down
    # And do the same for the dev configuration
    - docker compose -f ./compose/compose.dev.yaml build --pull
    - docker compose -f ./compose/compose.dev.yaml up --wait
    - docker compose -f ./compose/compose.dev.yaml down

  rules:
    - if: $CI_COMMIT_BRANCH
