# Compose overrides for local development
services:
  frontend:
    build:
      context: ./app/frontend
      target: dev-nginx
    depends_on:
      - frontend-dev
    develop:
      watch:
        - path: ./app/frontend/nginx.dev.conf
          action: sync+restart
          target: /etc/nginx/conf.d/default.conf

  frontend-dev:
    build:
      context: ./app/frontend
      target: dev-react
    develop:
      watch:
        - path: ./app/frontend
          include: package*.json
          action: rebuild
        - path: ./app/frontend
          ignore: # TODO: refine
            - package*.json
          action: sync
          target: /app
  backend:
    build:
      context: ./app/backend
    develop:
      watch:
        - path: ./app/backend/requirements.txt
          action: rebuild
        - path: ./app/backend/main.py
          action: sync+restart
          target: /app/main.py
        - path: ./app/backend
          ignore: # TODO: refine
            - requirements.txt
            - main.py
          action: sync
          target: /app
  model:
    build:
      context: ./model
    develop:
      watch:
        - path: ./model/requirements.txt
          action: rebuild
        - path: ./model/main.py
          action: sync+restart
          target: /app/main.py
        - path: ./model
          ignore: # refine
            - requirements.txt
            - main.py
          action: sync
          target: /app
