# Production configuration

name: random-iceberg

# Merge relevant configurations together
include:
  - path:
      - ./config/common.yaml
      - ./config/prod-common.yaml
      - ./config/latest-overrides.yaml
