# Common parts
services:
  # Frontend service (React)
  frontend:
    ports:
      - "8080:80" # nginx
    depends_on:
      - backend
    restart: unless-stopped

  # Backend service (FastAPI)
  backend:
    depends_on:
      - model
      - postgres
    restart: unless-stopped
    environment:
      BACKEND_WEB_ROOT: /api
      DB_USER: backend
      DB_DATABASE: backend
      DB_ADDRESS: postgres
      # DB_PASSWORD_FILE: /run/secrets/postgres_password_backend
      DB_PASSWORD: _backend
    secrets:
      - postgres_password_backend

  # Model service (ML predictions microservice)
  model:
    restart: unless-stopped

  # Database container (Postgres)
  postgres:
    build: ../postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      # POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_PASSWORD: _postgres
      BACKEND_PASSWORD: _backend
    secrets:
      - postgres_password
      - postgres_password_backend

volumes:
  postgres:

# As all the configurations are for local use only, just set the secrets here
secrets:
  postgres_password:
    environment: SECRET_POSTGRES_PASSWORD
  postgres_password_backend:
    environment: SECRET_POSTGRES_PASSWORD_BACKEND
