# Common parts
services:
  # Frontend service (React)
  frontend:
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8080:80" # nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Backend service (FastAPI)
  backend:
    restart: unless-stopped
    depends_on:
      model:
        condition: service_healthy
    environment:
      DB_USER: backend
      DB_DATABASE: backend
      DB_ADDRESS: postgres
      DB_PASSWORD: "${POSTGRES_PASSWORD_BACKEND:-_backend}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY:-_ultrasecurejwtsecretkey}"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Model service (FastAPI)
  model:
    restart: unless-stopped
    volumes:
      - model-data:/data
    environment:
      DATA_PREFIX: /data
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Database container (Postgres)
  postgres:
    build: ../postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-_postgres}"
      POSTGRES_PASSWORD_BACKEND: ${POSTGRES_PASSWORD_BACKEND:-_backend}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backend -d backend"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Database GUI (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-team@random.iceberg}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-Cheezus123}"
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      postgres:
        condition: service_healthy
    # healthcheck:
    #     test: ["CMD-SHELL", "curl -sf http://localhost/"] # curl is not available
    #     interval: 30s
    #     timeout: 10s
    #     retries: 3
    #     start_period: 30s

volumes:
  postgres-data:
  model-data:
