# Common parts
services:
  # Frontend service (React)
  frontend:
    ports:
      - "8080:80" # nginx
    depends_on:
      - backend
    restart: unless-stopped

  # Backend service (FastAPI)
  backend:
    depends_on:
      - model
      - postgres
    restart: unless-stopped
    environment:
      BACKEND_WEB_ROOT: /api
      DB_USER: backend
      DB_DATABASE: backend
      DB_ADDRESS: postgres
      DB_PASSWORD_FILE: /run/secrets/postgres_password_backend
    secrets:
      - postgres_password_backend

  # Model service (ML predictions microservice)
  model:
    restart: unless-stopped

  # Database container (Postgres)
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - ../postgres/initdb.d:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
      - postgres_password_backend

volumes:
  postgres:

# As all the configurations are for local use only, just set the secrets here
secrets:
  postgres_password:
    file: ../test_secrets/postgres_password
  postgres_password_backend:
    file: ../test_secrets/postgres_password_backend
